### ISSUE TITLE
Use numba to accelerate OpticalThickness calculation?

### ISSUE THREAD

**Issue by AndrewWilliams3142** [ddbkoll/PyRADS#14]
As noted in the examples/tests, most of the time taken to calculate the spectra is from the `OpticalThickness.compute_tau` calculation.

I've done a little bit of digging and it seems to me that the functions `computeAbsorption_fixedCutoff()`/`computeAbsorption()` (called by `getKappa_HITRAN()`) in `pyrads/Absorption_Crosssections_HITRAN2016.py` are the ones which cause this slowdown. 

This is because in both functions there exists a very large loop over the wavenumbers:

```python
for i in range(len(waveList)):
        n = waveList[i] # Wavenumber of the line
        #gam = gamList[i]*(p/1.013e5)*(296./T)**TExpList[i]  # DKOLL: old
        gam = getGamma(i)*(296./T)**TExpList[i]              # DKOLL: new. getGamma includes p-scaling
        #Temperature scaling of line strength
```

Given that there isn't anything particularly complex that happens inside this loop, I'm wondering whether it makes sense to try and accelerate this function using [numba](https://numba.pydata.org/). I'm playing around with this idea a bit now and I think that it should be possible, but the code in `Absorption_Crosssections_HITRAN2016.py` will have to be tidied up a bit. 

Specifically:
 - Remove `global` statements / make all function inputs _explicit_
 - Unpack class instances (eg. unpack everything in `params`) -- numba doesn't like classes at the moment

There might be more issues here, and I've only just started playing with the idea, but I'll try and keep a log here of what does/doesn't work. 

Also tagging @hdrake and @brian-rose here too, in case anyone's interested / has any thoughts on this / has already tried it?!

**Comment by brian-rose** [comment]
I haven't thought much about it beyond musing that acceleration with numba is probably a good idea :-)

It would be great to make some progress on #6 and add some tests to ensure that the package is portable and reproducible on different platforms. Acceleration without tests could be a recipe for trouble.

**Comment by AndrewWilliams3142** [comment]
Good point @brian-rose ! I'll start working on some tests this week. 

I've also added a setup.py in #13 , which seems to work when I tried it locally. I'm not sure how to wrap fortran build though.

**Comment by brian-rose** [comment]
The fortran wrapping can be a chore. The RRTMG wrapper for climlab could serve as a useful example.

**Comment by ddbkoll** [comment]
Numba does seem to speed things up significantly -- great work @AndrewWilliams3142 !

I've added a conda env so new PyRADS users can hopefully use this out-of-the-box. @brian-rose @AndrewWilliams3142 let me know if you have any other suggestions to increase user friendliness

**Comment by AndrewWilliams3142** [comment]
No worries @ddbkoll , happy to help! 

As @brian-rose said already, I think the next step should be to automate the fortran build ( and *fully* close #6 ), this will make it easier to add some unit tests as well. I did a dive into the climlab RRTMG wrapper as suggested, but I don't really know enough about conda/compilers to be able to follow the details sadly

**Comment by brian-rose** [comment]
@AndrewWilliams3142 it's not pretty! If I can find some time I will take another look at #6. I do think the automation of the build is important to make this package more portable and more testable.

**Comment by AndrewWilliams3142** [comment]
@brian-rose great! I just noticed your `minimalf2py` repo actually - I'll take a look at that and see if I can understand the automatic compilation process a bit better. Happy to be of help if i can

**Comment by brian-rose** [comment]
Yes, that's a good place to start (and I should have mentioned earlier). I created that repo specifically to help debug some build / CI issues.
