### ISSUE TITLE
OpticalThickness.py/compute_tau_H2ON2_CO2dilute

### ISSUE THREAD

**Issue by aromanro** [ddbkoll/PyRADS#2]
On line 63, in `compute_tau_H2ON2_CO2dilute`, `kappaCO2 = getKappa_HITRAN` is called with "H2O". Shouldn't be called with "CO2"?

**Comment by ddbkoll** [comment]
That's correct! Fixed now.
Note, there's a number of other issues that should still be fixed, I'll open an issue.
